### ISSUE TITLE
win10 1903 新系统设置 sourceFileMap 无效，只能克隆源代码到 C 盘根目录

### ISSUE THREAD

**Issue by bsed** [yim7/vscode-demo#1]

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/57275072-e429da00-70cf-11e9-93e5-e2c44175534a.png)

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/57275088-f0ae3280-70cf-11e9-9e17-1b1ff8e91083.png)

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/57275096-f60b7d00-70cf-11e9-9e72-e1090f73cb08.png)

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/57275137-1e937700-70d0-11e9-9a4d-981860928946.png)

**Comment by yim7** [comment]
win 请参考 readme [文件的流程操作，我在1.34.1版本下测试正常（当然我在[知乎](https://zhuanlan.zhihu.com/p/56161750)提到的问题也存在，这并不是一个非常好的方法）。你的截图，sourcefilemap参数显然不是根据我教程执行完成后的结果，cpdelldb 插件才支持 ‘*’ 通配符。你可以clone这个demo测试，需要稍微修改下路径。

**Comment by bsed** [comment]
tks
